
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.2"
    hooks:
    -   id: terraform_fmt
    -   id: terraform_tflint
    -   id: terraform_validate
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
  - id: terraform-docs-go
    args: ["markdown", "table","--output-file", "README.md", "."]

- repo: local
  hooks:
  - id: trivy
    name: Trivy security scan
    description: "Scan Repository with Trivy"
    language: script
    entry: ./trivy.sh
    pass_filenames: false
    always_run: true

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.26.3
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
    - id: check-dependabot
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.36.0
  hooks:
  - id: markdownlint-fix
  - id: markdownlint
